### PR TITLE
Add `try_` variants of `Assert` methods

### LINKED ISSUE #127: Question regarding "flaky" commands
I have a command that succeeds most of the time, but fails with some small probability. I would like to run it at most N times and declare success once some run succeeds, or fail if all N runs fail. (Something like what [retry](https://github.com/jimmycuadra/retry) does.)

By "fail," I mean say that a predicate doesn't match a command's `stdout`.

I would like to check each run using `assert_cmd` (because it's awesome). However, given that failure means panic, I can't see an easy way to do this.

Do you have any suggestions on how to accomplish what I've described using `assert_cmd`?

### PR DESCRIPTION
**Pull request by smoelius**
Closes #127

### CODE REVIEW

**Review by epage — APPROVED** [review]
Thanks!

**Comment by smoelius** [comment]
^ Is this the right way to satisfy "Lint Commits?"

**Comment by epage** [comment]
Yes.  Thanks.  Normally I give contributors a pass and fix it when merging.

**Comment by smoelius** [comment]
Thanks, @epage!

**Pull request merged**
